### PR TITLE
Remove assign by reference for 'new' which is not supported in PHP7+.…

### LINKED ISSUE #49: Version 3 wont install under PHP 7.x
Database upgrade following install fails with:
syntax error, unexpected 'new' (T_NEW) in xxx/wp-content/plugins/files/civicrm/extensions/uk.co.compucorp.civicrm.giftaid/CRM/Civigiftaid/Utils/Contribution.php, line 99

Settings site to PHP 5.6.31 allows db upgrade to pass

### PR DESCRIPTION
**Pull request by mattwire**
… Fixes #49

### CODE REVIEW

**Comment by davejenx** [comment]
This is duplicated by #74. The latter has been verified as fixing issue #73 which affects PHP 7. Makes sense to merge this one, as it came first and removes a couple of extra unnecessary (but harmless?) assigns by reference. We can then close #74.

**Comment by mattwire** [comment]
@jamienovick @guanhuan Can this be merged.  Seems a shame to have such a useful extension unusable out of the box on well over half of CiviCRM's installed userbase (PHP7+ accounts for over 5500 installs of CiviCRM - https://stats.civicrm.org/json/active-sites-server-php.json)

**Comment by jamienovick** [comment]
@mattwire  It's on the list and sorry we've not been able to get to this quite yet. Let me try and push it along.

**Comment by davejenx** [comment]
Thanks @jamienovick . Would be good to get @aydun's PR #68 merged too, as that fixes breakage on Civi 5.10.x .

**Pull request merged**
